### ISSUE TITLE
Including Fork and offering .deb

### ISSUE THREAD

**Issue by wasgehetdichdasan** [Stanko/ThinkPad-Fan-Control#2]
Hi,

is it possible to include the Fork and offering an .deb Package?

thanks for your work!

**Comment by Stanko** [comment]
Hi there, not sure what do you mean by including a fork? You are free to fork a repo and make changes.

Regarding the `.deb`, I'm not really maintaining this project, as I'm not using nor ThinkPad nor Linux anymore. If you can build deb package, I would be happy to put download mirror here.

Cheers!
