### ISSUE TITLE
18.04 , can not control fan on x240

### ISSUE THREAD

**Issue by alphaaurigae** [Stanko/ThinkPad-Fan-Control#4]
Hi, 

trying to find a solution to regulate the fan of my **x240** running **18.04 xubuntu**. (changed gksu to sudo)

I have build your app and run it with `sudo` but apparently the app cant control the fan speed on my installation.

On the GUI i read `"Youre not running the kernel with thinkpad patch"`
Same result with root.

```
$ sudo '/home/a/ThinkPad-Fan-Control/tpfc_start.sh'

(tp_fan_control:1854): Gtk-WARNING **: 21:09:35.345: GtkSpinButton: setting an adjustment with non-zero page size is deprecated

(tp_fan_control:1854): Gtk-WARNING **: 21:09:35.345: GtkSpinButton: setting an adjustment with non-zero page size is deprecated

(tp_fan_control:1854): Gtk-WARNING **: 21:09:35.345: GtkSpinButton: setting an adjustment with non-zero page size is deprecated
sh: echo: I/O error
** Welcome! **
** ThinkPad fan control by Stanko! **
** Fan control changed to auto **
sh: echo: I/O error
** Speed level changed to auto **
sh: echo: I/O error
** Speed level changed to 1 **
sh: echo: I/O error
** Speed level changed to 7 **
```

**Comment by alphaaurigae** [comment]
just have seen your comment the repo isnt supported anymore ... found an alternative btw https://github.com/devxpy/thinkfan-control-gui

**Comment by Stanko** [comment]
Glad you found the alternative, cheers!
