### ISSUE TITLE
Updated Fork to the Program

### ISSUE THREAD

**Issue by ForgedTurbo** [Stanko/ThinkPad-Fan-Control#6]
Greetings Stanko,
First of All. Thank you for creating this program!!
The basics of it works great, but due to changes to the Linux Kernel, the start-up scripts and the README.md are outdated.
I switched to Linux (Fedora 30) not too long ago with my T410s as an On-the-Go machine.
Since I am not too good with programming, and I don't want to ruin your project, I created a Fork and did some adjustments so the program would work nowadays with newer Linux Versions.
It probably sounds pretty weird, but I would like to ask if it is possible for you to maybe recommend my Fork in your Project?
Since your project has a great reputation and is referenced in many Wikis, but is not working for the Current Linux Versions. Causing a bit of trouble for newcomers to Linux like me.
Again, Thank You. And please let me know your thoughts.

Best Regards,
Tony (ForgedTurbo)

**Comment by Stanko** [comment]
Hey @ForgedTurbo,
Of course, as I'm not actively maintaining this repo, that is a great addition. Thank you for your help!

I updated the readme file
https://github.com/Stanko/ThinkPad-Fan-Control/blob/master/README.md

Cheers!
